export const INIT_SAVE_NEW_USER = 'INIT_SAVE_NEW_USER';
export const SAVE_NEW_USER = 'SAVE_NEW_USER';
export const SAVE_NEW_USER_REQUEST_NOT_PROCESSED = 'SAVE_NEW_USER_REQUEST_NOT_PROCESSED ';

export const INIT_AUTH = 'INIT_AUTH';