export const INIT_SAVE_NEW_USER = 'INIT_SAVE_NEW_USER';
export const SAVE_NEW_USER = 'SAVE_NEW_USER';
export const SAVE_NEW_USER_REQUEST_NOT_PROCESSED = 'SAVE_NEW_USER_REQUEST_NOT_PROCESSED';

export const INIT_LOGIN_USER = 'INIT_LOGIN_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_REQUEST_NOT_PROCESSED = 'LOGIN_USER_REQUEST_NOT_PROCESSED';

export const INIT_LOGOUT_USER = 'INIT_LOGOUT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const INIT_GET_PROFILE = 'INIT_GET_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const PROFILE_IS_LOADING = 'PROFILE_IS_LOADING';

export const INIT_GET_PROFILES = 'INIT_GET_PROFILES';
export const GET_PROFILES = 'GET_PROFILES';

export const INIT_CREATE_PROFILE = 'INIT_CREATE_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const CREATE_PROFILE_REQUEST_NOT_PROCESSED = 'CREATE_PROFILE_REQUEST_NOT_PROCESSED';

export const INIT_UPDATE_PROFILE = 'INIT_UPDATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_REQUEST_NOT_PROCESSED = 'UPDATE_PROFILE_REQUEST_NOT_PROCESSED';

export const INIT_REMOVE_PROFILE_ALONG_WITH_USER = 'INIT_REMOVE_PROFILE_ALONG_WITH_USER';
export const REMOVE_PROFILE_ALONG_WITH_USER = 'REMOVE_PROFILE_ALONG_WITH_USER';
export const REMOVE_PROFILE_ALONG_WITH_USER_REQUEST_NOT_PROCESSED =
  'REMOVE_PROFILE_ALONG_WITH_USER_REQUEST_NOT_PROCESSED';

export const INIT_ADD_EXPERIENCE = 'INIT_ADD_EXPERIENCE';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_EXPERIENCE_REQUEST_NOT_PROCESSED = 'ADD_EXPERIENCE_REQUEST_NOT_PROCESSED';

export const INIT_REMOVE_EXPERIENCE = 'INIT_REMOVE_EXPERIENCE';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const REMOVE_EXPERIENCE_REQUEST_NOT_PROCESSED = 'REMOVE_EXPERIENCE_REQUEST_NOT_PROCESSED';

export const INIT_ADD_EDUCATION = 'INIT_ADD_EDUCATION ';
export const ADD_EDUCATION = 'ADD_EDUCATION ';
export const ADD_EDUCATION_REQUEST_NOT_PROCESSED = 'ADD_EDUCATION_REQUEST_NOT_PROCESSED';

export const CLEAN_UP_CURRENT_PROFILE = 'CLEAN_UP_CURRENT_PROFILE ';

export const CLEAN_UP_ERRORS = 'CLEAN_UP_ERRORS';