import React, {Component} from 'react';
import {connect} from 'react-redux';
import PropTypes from 'prop-types';
import {Link} from 'react-router-dom';

class PostItem extends Component {
  onDeleteClick = () => {
    console.log('delete', this.props.post._id);
  };

  render() {
    const {post, auth} = this.props;
    return (
      <div className="card card-body mb-3">
        <div className="row">
          <div className="col-md-2">
            <a href={`/developers/user/${post.user}`}>
              <img className="rounded-circle d-none d-md-block"
                   src={post.avatar}
                   alt="User avatar"
                   title="Avatar generated by Gravatar"/>
            </a>
            <br/>
            <p className="text-center">{post.name}</p>
          </div>
          <div className="col-md-10">
            <p className="lead">{post.text}</p>
            <button type="button" className="btn btn-light mr-1">
              <i className="text-info fas fa-thumbs-up"></i>
              <span className="badge badge-light">{post.likes.length}</span>
            </button>
            <button type="button" className="btn btn-light mr-1">
              <i className="text-secondary fas fa-thumbs-down"></i>
            </button>
            <Link className="btn btn-info mr-1" to={`posts/${post._id}`}>
              Comments
            </Link>
            {post.user === auth.user.id ? (
              <button
                onClick={this.onDeleteClick}
                type="button"
                className="btn btn-danger mr-1">
                <i className="fas fa-times"/>
              </button>
            ) : null}
          </div>
        </div>
      </div>
    );
  }
}

PostItem.propTypes = {
  auth: PropTypes.object.isRequired,
  post: PropTypes.object.isRequired,
};

const mapStateToProps = state => {
  return {
    auth: state.auth,
  };
};

export default connect(mapStateToProps, null)(PostItem);